### ISSUE TITLE
[Enhancement 💡] Add missing tags for more mod compatibility

### ISSUE THREAD

**Issue by ffuentesm** [Lucreeper74/Create-Metallurgy#10]
**Describe the solution you'd like**
Add the forge:moltern_{material} tag to the fluids/molten buckets so the fluids are interchangeable with other mods that use molten metal fluids. (e.i. Tinkers'Construct)
Also, remove the Minecraft:lava tag from the molten metal fluids, this causes the molten fluids to be eligible to be "Liquid Fuel" in mods that use Lava as a fuel source. 

For the coal coke, could you use the forge:coal_coke and minecraft:coal tags?

You are also missing the forge:storage_block/{material} tag for raw Tungsten block, Tungsten block, Steel Block, and coal Coke block. And, even if you use wolframite for the item name, the tag compatibility would call the Tungsten naming for most mods. 

Also, could you add a compatibility to Create:Vintage & improvements Belt Grinder?

**Comment by Lucreeper74** [comment]
Hi @ffuentesm!
- For molten fluids there is already tags "forge:molten_{material}" added on this [commit](https://github.com/Lucreeper74/Create-Metallurgy/commit/3b5ae42176ad3f208e09a9992e2599e85a78792f) and available in v0.0.3 of Create Metallurgy.
- For lava tags, I don't even thought about possibly conflicts with mods that use it for fuel. Fixed in this [commit](https://github.com/Lucreeper74/Create-Metallurgy/commit/eeb9620d18349755cb4795eaf771c0d557036620)
- For "forge:storage/{material} I will take a look at how others mod using it to avoid making miss take, will be added soon.
- For Coke coal tag, i will also take a look and added soon
- And finally for compat with Create:V&I, what do you mean exactly, make mine Belt Grinder recipes compatible with their?

*Also, thanks to taking the time to propose enhancements, that help me to improve Create Metallurgy 👍*

**Comment by ffuentesm** [comment]
Thanks for the fixes. 

I mainly look at Immersive engineering and Thermal Foundations for their use of the tags. 
if you were using minecraft:lava tag for easy fluid physics, I recall that 1.19.2 added a fluid API for that, so you could add your own physics to fluids without tagging it as lava or water. 

And yes for Create: V&I, just make the recipes compatible between both belt grinders, since both mods add the same machine.

**Comment by Lucreeper74** [comment]
> Thanks for the fixes.
> 
> I mainly look at Immersive engineering and Thermal Foundations for their use of the tags. if you were using minecraft:lava tag for easy fluid physics, I recall that 1.19.2 added a fluid API for that, so you could add your own physics to fluids without tagging it as lava or water.
> 
> And yes for Create: V&I, just make the recipes compatible between both belt grinders, since both mods add the same machine.

I was using minecraft:lava tag since the initial commit, I wanted to see if it could help with the behavior of the liquid so that it burns the player, in the end no and I left it without really asking myself the question. I will make molten fluids burning behavior soon so thx, I will take a look to it.

I have talk with Create:V&I dev to ask him if I could add a similar block cause I planned to add specific features especially with my mod so yea, its duplicated when use both mod.

I will keep this issue open until I added the tags and maybe consider compatibility with Create:V&I.

**Comment by ffuentesm** [comment]
> * For molten fluids there is already tags "forge:molten_{material}" added on this [commit](https://github.com/Lucreeper74/Create-Metallurgy/commit/3b5ae42176ad3f208e09a9992e2599e85a78792f) and available in v0.0.3 of Create Metallurgy.

Are you sure? I am on version 0.0.3 on 1.19.2, and when I check the fluid tag on the molten buckets, I only get the lava tag. 
![image](https://github.com/Lucreeper74/Create-Metallurgy/assets/44974827/f477758c-a0e5-473c-ad61-fc1968e1ef61)

I am using Mantle to get the fluid tags from the items, and I am comparing them to the TiC Monten Buckets, since TiC adds many compatible fluids to the game. 

As you can see, the Metallurgy bucket lacks the molten fluid tags. 
![image](https://github.com/Lucreeper74/Create-Metallurgy/assets/44974827/da5a00f3-f553-40c7-8c2e-47ea477fbd68)

The same happens to other materials. 
![image](https://github.com/Lucreeper74/Create-Metallurgy/assets/44974827/4b0b0281-06a2-40df-9859-d856a5546626)
![image](https://github.com/Lucreeper74/Create-Metallurgy/assets/44974827/df770785-ec09-4ca5-9d32-9241d8828276)

Also, on your basin and casting table, could you use fluid tags as input instead of item id? 
That way users could use fluids from other mods on the tables/basin

**Comment by Lucreeper74** [comment]
Nevermind, I'm stupid. I forgot to data gen that will add tags to the game, I just added the instruction for the data generator.
And for tags in input of recipes added by Create Metallurgy, this is planned. A few minutes ago, another person propose it on Discord too.

Would work properly now [Commit](https://github.com/Lucreeper74/Create-Metallurgy/commit/67a18e42449c150f3fd63070c250b63def8fd202)

**Comment by Lucreeper74** [comment]
Would work properly now [Commit](https://github.com/Lucreeper74/Create-Metallurgy/commit/67a18e42449c150f3fd63070c250b63def8fd202)

**Comment by Lucreeper74** [comment]
Hey @ffuentesm :wave:!
I have added "Forge:storage_blocks/materials" and change coke tag from "Forge:coke" to "Forge:coal_coke" in this [commit](https://github.com/Lucreeper74/Create-Metallurgy/commit/5e716bf2285c24db7d11d5b4d0f1a359f5afa030)
