### ISSUE TITLE
On the capacity of casting basin

### ISSUE THREAD

**Issue by Qi-Month** [Lucreeper74/Create-Metallurgy#11]
During the Modpack production process, it was found that the maximum capacity of casting basin can only reach 810mb. Can you consider adjusting the maximum capacity to 1000mb?

**Comment by Lucreeper74** [comment]
Hey @Qi-Month!
I made this because an ingot is 90mb like  Tinker Construct. And if i made Casting basin holding up to 1000mb of fluid, each time a recipe would end, a small amount of unused fluid will stay that can be annoying.

**Comment by ffuentesm** [comment]
Yeah, if I recall, the TiC basin is not an interactable tank, so it has no interaction with buckets or other fluid storage items. 
So you can not add or remove fluids from a basin manually. 
![image](https://github.com/Lucreeper74/Create-Metallurgy/assets/44974827/17f10bbc-697c-49a3-b4a7-355cfcec07b0)

The only way to interact with a basin is with a faucet or an in/out pipe.

**Comment by Qi-Month** [comment]
> Hey @Qi-Month! 嘿 ！ I made this because an ingot is 90mb like Tinker Construct. And if i made Casting basin holding up to 1000mb of fluid, each time a recipe would end, a small amount of unused fluid will stay that can be annoying.我做这个是因为像 Tinker Construct 一样，一个锭有 90mb。如果我制作的铸造盆可容纳 1000mb 的液体，则每次配方结束时，都会留下少量未使用的液体，这可能会很烦人。

So I would like to ask if I can refer to TCon to determine the fluid height according to the quantity.

In the process of writing, I will also refer to TCon to make a part of the 1000mb cooling Recipes, but when I find that the maximum capacity can only be 810mb, it will be very complicated, and the capacity of exactly one bucket is also 1000mb, so can the fluid be conveniently introduced into the basin manually?

By the way, if you can consider referring to TCon, can basin also use molds?

**Comment by Lucreeper74** [comment]
> > Hey @Qi-Month! 嘿 ！ I made this because an ingot is 90mb like Tinker Construct. And if i made Casting basin holding up to 1000mb of fluid, each time a recipe would end, a small amount of unused fluid will stay that can be annoying.我做这个是因为像 Tinker Construct 一样，一个锭有 90mb。如果我制作的铸造盆可容纳 1000mb 的液体，则每次配方结束时，都会留下少量未使用的液体，这可能会很烦人。
> 
> So I would like to ask if I can refer to TCon to determine the fluid height according to the quantity.
> 
> In the process of writing, I will also refer to TCon to make a part of the 1000mb cooling Recipes, but when I find that the maximum capacity can only be 810mb, it will be very complicated, and the capacity of exactly one bucket is also 1000mb, so can the fluid be conveniently introduced into the basin manually?
> 
> By the way, if you can consider referring to TCon, can basin also use molds?

Sorry for your disapointing but like @ffuentesm said, I make my Casting Basin according to the TC one.
I don't think it would be better to change this because basically the Casting Basin is used to cast blocks, so 9x 90mb. Maybe in the future I will make a special bigger Casting Basin to allow certain types of larger recipes with molds and adding original features with it ?

**Comment by ffuentesm** [comment]
Instead of a new basin, I would just suggest a "basin mold" that would let you add more fluid according to the recipe. 
So you can use the same basin, which lets you cast blocks (810mb), and let you pour other liquid amounts. 

Also, I feel @Qi-Month is just trying to make the Casting Basin into the normal Create Basin. They are very different since the Create Basin was made for Bucket interaction, so it allows the 1000mb of fluid, but the Casting Basin was meant for Ingot/Block casting which uses multiples of 9. 

The only way around would be to make a "block mold" that you would apply to the basin to limit the fluid insert to 810mb. 
But that would just make the basin itself obsolete and this whole thing a moot point.

**Comment by Lucreeper74** [comment]
> Instead of a new basin, I would just suggest a "basin mold" that would let you add more fluid according to the recipe. So you can use the same basin, which you lets you cast blocks (810mb), and let you pour other liquid amounts.

Yes, I don't know yet how this will evolve.

> Also, I feel you are just trying to make the Casting Basin into the normal Create Basin.
They are very different since the Create Basin was made for Bucket interaction, so it allows the 1000mb of fluid, but the Casting Basin was meant for Ingot/Block casting which uses multiples of 9.
The only way around would be to make a "block mold" that you would apply to the basin to limit the fluid insert to 810mb.
But that would just make the basin itself absolute and this whole thing a moot point.

Did you talk to me or @Qi-Month ?

**Comment by ffuentesm** [comment]
A bit of both. 
Just trying to brainstorm the reason why the casting basin is the way it is. You do not pour molten Metal from a bucket into the casting basin, you pour it in the Foundry. And the Foundry is where you then pour into the Casting Basin. 

Also, there should be no problem with that, since the Foundry basin only accepts 9 items, so it would never be able to make up 1000mb to be picked by a bucket. (Or any amount where the remainder fluid would be 0)

Actually, the only way I see where someone could make up the 1000mb was by using nuggets (10mb) to round the number to 1000mb. 

On a side note. 
I feel that using Supper Heated on the foundry is not really "great", mostly due to how Base Create has the Brass recipe to be just a Heated Burner. 
![image](https://github.com/Lucreeper74/Create-Metallurgy/assets/44974827/e9084cb7-98be-4dfa-88a4-70c8e81e9b39)

When comparing to Tinkers'Construct, I would see the Super Heated as the Blazing BLood equivalent. So for Making Netherite Alloy and other high heat recipes. 

Also, would be nice if we could create the andesite Alloy using the Foundry. Make it a cheaper recipe by using this method. 
Since you need 2 nuggets and 2 andesite to have 1 Andesite Alloy. 
You could have it so you pour 1 Zinc/iron ingot into the casting basin to create 1 andesite block to create 1 Andesite Alloy block.
![image](https://github.com/Lucreeper74/Create-Metallurgy/assets/44974827/b5434e4e-f018-4606-b786-f29694211ae9)

**Comment by Lucreeper74** [comment]
Sorry for being late, I'm currently off (see reasons on Created Metallurgy discord). Yes, blaze burner heat level will be balance, and, yes andesite alloy can be a good idea, but Create add the first version with crafting table (2 nugget + 2 andesite = 1 andesite Alloy) and another with mixer (1 nugget + 1 andesite = 1 andesite Alloy) without any heat level required so it would be useless to my point of view ?

**Comment by ffuentesm** [comment]
@Lucreeper74 my suggestion was for casting 1 ingot (9 nuggets) + 1 Andesite = 1 Andesite Alloy block (9 Andesite Alloy)
This way you just use 1 andesite block for a batch crafter. 
You would still use 9 nuggets for this, but is faster, and the molten fluid makes up for how much less stone is used in the recipe.

**Comment by Lucreeper74** [comment]
Oh yes, sorry, misunderstanding... That is definitely more interesting!

**Comment by ffuentesm** [comment]
Also, another suggestion would be to use the Rod casting pattern to cast the Shafts with molten andesite alloy. 
Same with stripped logs with their different casins.
