### ISSUE TITLE
[BUG 🐜] Coke Block mislabeled as a Steel Storage Block, causing issues with AlmostUnified

### ISSUE THREAD

**Issue by ratemisia** [Lucreeper74/Create-Metallurgy#25]
**Describe the bug**

The createmetallurgy:coke_block is tagged #forge:storage_blocks/steel. With other mods that require tag items for steel, this means you can use a Coke Block instead of a Steel Block in crafting recipes. And with the mod AlmostUnified, this means crafting 9 Coke in a crafting table will produce a Steel Block. 

**To Reproduce**
1. Enable Advanced Tooltips
2. Hover over a Coke Block
3. See tag #forge:storage_blocks/steel

**Expected behavior**
I expected the Coke Block to be labeled as #forge:storage_blocks/coke or otherwise have the tag $forge:storage_blocks/steel absent. Removing this tag from the Coke Block would eliminate all undesired crafting behavior.

**Screenshots**
![image](https://github.com/user-attachments/assets/6ce0c8b1-86f4-41dc-906e-bcb583cb3392)

**Environment:**
 - Minecraft 1.20.1, NeoForge version 47.1.106
 - Create version 0.5.1.h
 - Create Metallurgy version 0.0.5-1.20.1
 - AlmostUnified and (in my case) Create: The Factory Must Grow, although any other mod with a Steel Block would have the same effect

**Additional context**
The undesired behavior isn't obvious without AlmostUnified, but would still partially appear when Metallurgy is in an environment with any recipes that take #forge:storage_blocks/steel as a tag item (as Coke Blocks would be craftable as a Block of Steel). This should be a very simple fix, as removing the tag from the Coke Block would eliminate all undesired behavior.

**Comment by Lucreeper74** [comment]
Hey @ratemisia 👋 
No worries, its an known issue and its has been fixed in this [commit](https://github.com/Lucreeper74/Create-Metallurgy/commit/f5493e0dadd74420755db259bee65a458ebfbbb2), sorry for you disappointment for now!
However, thanks you very much taking the time to make an ticket that detailed. That really help me to improve Create Metallurgy. Also, as you can see, Create Metallurgy developpement is very slow for now, you can join the Discord to see the reason.
