### ISSUE TITLE
[BUG 🐜] Foundry Basin Not Recognizing the casting table or basin.

### ISSUE THREAD

**Issue by CravenCraft** [Lucreeper74/Create-Metallurgy#39]
**Describe the bug**
The foundry basin should automatically open its chute when it recognizes the casting table or basin is next to it and one block below, but currently it requires a wrench to manually configure that.

**To Reproduce**
1. Fill the foundry basin with a molten metal.
2. Place a casting table or casting basin next to it and one bock below (similar to how Create's vanilla basin would work).

**Expected behavior**
The foundry basin should automatically open its chute when it recognizes the casting table or basin is next to it and one block below.

**Screenshots**
![image](https://github.com/user-attachments/assets/9f8b4c13-1efb-491c-9e5b-5112704e1ac8)

**Environment:**
 - MC/Forge version: 1.20.1 - Forge
 - Create version: 1.20.1-0.5.1.j
 - Create Metallurgy version: 0.0.6-1.20.1

**Comment by Lucreeper74** [comment]
Hey @CravenCraft !
Yes, its totally normal, not an issue, I rework the code for the faucet on Casting Basins. It no longer detect fluid tanks below it. You need to manually configure it. This reducing lag (For detecting right fluid tanks that require lot of tests) and mainly because its incompatible with the way i codded Casting Blocks. Sorry for late reply.

**Comment by CravenCraft** [comment]
Gotcha. Just making sure! One thing I'd add is to maybe update the ponder documentation. I think it still mentions that it's automatic.

**Comment by Lucreeper74** [comment]
Yes, forgot about that. Planned for the next update! Anything else? Can I close this post?

**Comment by CravenCraft** [comment]
Sounds good. Thanks for the quick feedback! And yeah all good to close the issue.
